name: Linting and Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  run-checks-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install --no-save
      - name: Run eslint - linting
        run: npm run lint
      - name: Check formatting
        run: npm run check
      - name: Run unit tests
        run: npm test
